### ISSUE TITLE
Flickering in 14.1.2

### ISSUE THREAD

**Issue by roelvangils** [briankendall/forceFullDesktopBar#19]
After I upgraded to macOS 14.1.2 (23B92) on my M2 Max, I get [this flickering](https://scr.11ways.be/V913Bt0x).

I think it's related to the **forceFullDesktopBar** utility, because when I quit all applications and uninstall the hack, it's gone. After I reinstall the hack (with the `install.sh` script), the flickering is back.

If you need anything else to be able to reproduce this effect, let me know! 🙂

**Comment by briankendall** [comment]
That's quite strange. Could you try an experiment for me:

1. Uninstall forceFullDesktopBar so that there's no flickering and the desktop previews are not automatically expanded
2. Move the mouse cursor to the top of the screen
3. Trigger Mission Control (the desktop previews should be fully expanded because of the mouse position)
4. Let me know if there's any flicking in this case

**Comment by roelvangils** [comment]
Thank you, Brian! I followed your advice and there was indeed no flickering with forceFullDesktopBar disabled. After reinstalling forceFullDesktopBar and rebooting, the problem disappeared completely. forceFullDesktopBar now functions as it did before. Perhaps it was just a glitch? 🤷🏼
