### ISSUE TITLE
Stopped working after a security update on Mojave

### ISSUE THREAD

**Issue by Vitkarus** [briankendall/forceFullDesktopBar#9]
Today I installed the latest security updates for Mojave and forceFullDesktopBar has stopped working. I tried to disable SIP and reinstall the utility several times, but nothing worked. What could be the problem?

**Comment by briankendall** [comment]
Looks like the new security update has broken mach_inject, which forceFullDesktopBar relies on to modify the Dock. I've created an issue on its github page and with any luck there's a fix. mach_inject is some deep black magic that I have very little understanding of, though, so this likely isn't something I can fix on my own.

For situations like these I recommend using [missionControlFullDesktopBar](https://github.com/briankendall/missionControlFullDesktopBar) as an alternative since it doesn't rely on code injection, though it's admittedly not as good, especially when using a trackpad.

**Comment by Vitkarus** [comment]
Got it, let's hope it would be fixed soon

**Comment by Brin-o** [comment]
Hi, has this been fixed?

**Comment by briankendall** [comment]
@Brin-o It might be actually. I just tested it out on a fully up-to-date 10.14.6 system (so security update 2021-05 is installed), and forceFullDesktopBar was still working.

@Vitkarus Are you still able to reproduce this issue?

**Comment by Vitkarus** [comment]
@briankendall @Brin-o I’m currently using forceFullDesktopBar on latest versions of Mojave and Catalina, and on both machines it works without any issue.

**Comment by briankendall** [comment]
Thanks for the update. I'm going to go ahead and close this issue then. If this comes back feel free to post a comment and request it be reopened.
